apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vulcan.fullname" . }}-dogstatsd
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: dogstatsd
type: Opaque
data:
  DD_API_KEY: {{ .Values.dogstatsd.apiKey | b64enc | quote }}
