{{- if .Values.sqsExporter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulcan.fullname" . }}-sqsexporter
  labels:
    {{- include "vulcan.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vulcan.name" . }}-sqsexporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vulcan.name" . }}-sqsexporter
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9384'
        {{- with .Values.sqsExporter.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "vulcan.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sqs-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sqsExporter.image.repository }}:{{ .Values.sqsExporter.image.tag }}"
          imagePullPolicy: {{ .Values.sqsExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9384
              protocol: TCP
          env:
          - name: SQS_QUEUE_NAME_PREFIX
            value: {{ .Values.sqsExporter.queueNamePrefix }}
          {{- if .Values.global.sqs.enabled }}
          - name: SQS_ENDPOINT
            value: "{{ include "sqsEndpoint" . }}"
          - name: AWS_ACCESS_KEY_ID
            value: TBD
          - name: AWS_SECRET_ACCESS_KEY
            value: TBD
          {{- end }}
          resources:
            {{- toYaml .Values.sqsExporter.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
