apiVersion: v2
name: vulcan
description: A Helm chart for deploying Vulcan
home: https://github.com/adevinta/vulcan-charts
icon: https://raw.githubusercontent.com/adevinta/vulcan-charts/master/docs/logo/vulcan.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.5.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

dependencies:
- name: postgresql
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled

maintainers:
  - email: vulcan@adevinta.com
    name: Adevinta
