{{- $_ := (set .Values "comp" .Values.reportsgenerator) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportsgenerator.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/secrets: {{ include "reportsgenerator-secrets" . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
    spec:
      {{- if .Values.comp.initContainers }}
      initContainers:
        {{ tpl (toYaml .Values.comp.initContainers) . | nindent 8 }}
      {{- end }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: PG_HOST
            value: {{ include "pg.host" . | quote }}
          - name: PG_NAME
            value: {{ include "pg.database" . | quote }}
          - name: PG_USER
            value: {{ include "pg.username" . | quote }}
          - name: PG_PORT
            value: {{ include "pg.port" . | quote }}
          - name: PG_SSLMODE
            value: {{ include "pg.sslMode" . | quote }}
          - name: PG_CA_B64
            value: {{ include "pg.b64ca" . | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: SQS_QUEUE_ARN
            value: {{ tpl .Values.comp.conf.queueArn .| quote }}
          {{- with .Values.comp.conf.sqsNumProcessors }}
          - name: SQS_NUM_PROCESSORS
            value: {{ . | quote }}
          {{- end }}
          - name: SES_REGION
            value: {{ .Values.comp.conf.ses.region | default (include "region" .) | quote }}
          - name: SES_FROM
            value: {{ .Values.comp.conf.ses.from | quote }}
          - name: SES_CC
            value: {{ .Values.comp.conf.ses.cc | quote }}
          - name: LIVEREPORT_EMAIL_SUBJECT
            value: {{ .Values.comp.conf.generators.livereport.emailSubject | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "reportsgenerator.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
          volumeMounts:
          {{- include "common-deployment-volumeMounts" . | nindent 12 }}
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
