apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "api.fullname" . }}
  name: {{ include "api.fullname" . }}
type: Opaque
data:
  PG_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  SECRET_KEY: {{ .Values.conf.secretKey | b64enc | quote }}
  AWSCATALOGUE_KEY: {{ .Values.conf.awscatalogue.key | b64enc | quote }}
